DROP TABLE IF EXISTS bids CASCADE;

CREATE TABLE bids (
  id SERIAL PRIMARY KEY NOT NULL,
  provider_bid_id INTEGER REFERENCES provider_bids(id) ON DELETE CASCADE,
  job_posting_id INTEGER REFERENCES job_postings(id) ON DELETE CASCADE
);